Repository cristighr1995/Holiholic, pull requests merged in 2018-11, with the labels that each got.

#1 [HH-1][Login] Create login module
  holiholic_login/.gitignore
  holiholic_login/pom.xml
  holiholic_login/src/main/java/com/holiholic/login/HoliholicLoginApplication.java
  holiholic_login/src/main/java/com/holiholic/login/constant/Constants.java
  holiholic_login/src/main/java/com/holiholic/login/controllers/AuthController.java
  holiholic_login/src/main/java/com/holiholic/login/database/DatabaseManager.java
  holiholic_login/src/main/java/com/holiholic/login/login/LoginManager.java
  holiholic_login/src/main/resources/application.properties
Labels: enhancement

#2 [HH-2][Database] Create database module
  holiholic_database/.gitignore
  holiholic_database/pom.xml
  holiholic_database/src/main/java/com/holiholic/database/DatabaseManager.java
  holiholic_database/src/main/java/com/holiholic/database/HoliholicDatabaseApplication.java
  holiholic_database/src/main/java/com/holiholic/database/constant/Constants.java
  holiholic_database/src/main/java/com/holiholic/database/controller/LoginController.java
  holiholic_database/src/main/resources/application.properties
Labels: enhancement

#3 [HH-3][Planner] Create planner module
  holiholic_planner/.gitignore
  holiholic_planner/.mvn/wrapper/maven-wrapper.jar
  holiholic_planner/.mvn/wrapper/maven-wrapper.properties
  holiholic_planner/db_backup/bucharest.json
  holiholic_planner/db_backup/bucharest_driving.txt
  holiholic_planner/db_backup/bucharest_restaurants.json
  holiholic_planner/db_backup/bucharest_traffic.txt
  holiholic_planner/db_backup/bucharest_walking.txt
  holiholic_planner/db_backup/bucharest_weather.txt
  holiholic_planner/mvnw
  holiholic_planner/mvnw.cmd
  holiholic_planner/pom.xml
  holiholic_planner/scripts/.gitignore
  holiholic_planner/scripts/pom.xml
  holiholic_planner/scripts/src/main/java/UpdateManager.java
  holiholic_planner/src/main/java/com/holiholic/planner/HoliholicPlannerApplication.java
  holiholic_planner/src/main/java/com/holiholic/planner/constant/Constants.java
  holiholic_planner/src/main/java/com/holiholic/planner/controllers/PlacesController.java
  holiholic_planner/src/main/java/com/holiholic/planner/controllers/PlannerController.java
  holiholic_planner/src/main/java/com/holiholic/planner/database/DatabaseManager.java
  holiholic_planner/src/main/java/com/holiholic/planner/models/Place.java
  holiholic_planner/src/main/java/com/holiholic/planner/planner/PlanManager.java
  holiholic_planner/src/main/java/com/holiholic/planner/planner/Planner.java
  holiholic_planner/src/main/java/com/holiholic/planner/planner/VisitTask.java
  holiholic_planner/src/main/java/com/holiholic/planner/travel/City.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/CloneFactory.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/Enums.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/GeoPosition.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/Interval.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/Meal.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/MealFactory.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/OpeningPeriod.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/Reader.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/ThreadManager.java
  holiholic_planner/src/main/java/com/holiholic/planner/utils/WeatherForecastInformation.java
  holiholic_planner/src/main/resources/application.properties
Labels: enhancement

#4 [HH-4][FOLLOW] Create follow module
  holiholic_database/src/main/java/com/holiholic/database/DatabaseManager.java
  holiholic_database/src/main/java/com/holiholic/database/constant/Constants.java
  holiholic_database/src/main/java/com/holiholic/database/controller/PeopleController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/TopicsController.java
  holiholic_follow/.gitignore
  holiholic_follow/pom.xml
  holiholic_follow/src/main/java/com/holiholic/follow/HoliholicFollowApplication.java
  holiholic_follow/src/main/java/com/holiholic/follow/constant/Constants.java
  holiholic_follow/src/main/java/com/holiholic/follow/controllers/PeopleController.java
  holiholic_follow/src/main/java/com/holiholic/follow/controllers/TopicsController.java
  holiholic_follow/src/main/java/com/holiholic/follow/database/DatabaseManager.java
  holiholic_follow/src/main/java/com/holiholic/follow/follow/PeopleManager.java
  holiholic_follow/src/main/java/com/holiholic/follow/follow/TopicsManager.java
  holiholic_follow/src/main/resources/application.properties
Labels: enhancement

#5 [HH-5][FEED] Create feed module
  holiholic_database/src/main/java/com/holiholic/database/DatabaseManager.java
  holiholic_database/src/main/java/com/holiholic/database/constant/Constants.java
  holiholic_database/src/main/java/com/holiholic/database/controller/FeedController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/PostController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/QuestionsController.java
  holiholic_database/src/main/java/com/holiholic/database/feed/Comment.java
  holiholic_database/src/main/java/com/holiholic/database/feed/Feed.java
  holiholic_database/src/main/java/com/holiholic/database/feed/FeedEditHandler.java
  holiholic_database/src/main/java/com/holiholic/database/feed/ICommentAction.java
  holiholic_database/src/main/java/com/holiholic/database/feed/IFeedEditable.java
  holiholic_database/src/main/java/com/holiholic/database/feed/Post.java
  holiholic_database/src/main/java/com/holiholic/database/feed/Question.java
  holiholic_feed/.gitignore
  holiholic_feed/pom.xml
  holiholic_feed/src/main/java/com/holiholic/feed/HoliholicFeedApplication.java
  holiholic_feed/src/main/java/com/holiholic/feed/constant/Constants.java
  holiholic_feed/src/main/java/com/holiholic/feed/controller/FeedController.java
  holiholic_feed/src/main/java/com/holiholic/feed/controller/PostController.java
  holiholic_feed/src/main/java/com/holiholic/feed/controller/QuestionsController.java
  holiholic_feed/src/main/java/com/holiholic/feed/database/DatabaseManager.java
  holiholic_feed/src/main/resources/application.properties
Labels: enhancement, in progress

#7 [HH-7] Change md5Key into uid
  holiholic_database/src/main/java/com/holiholic/database/DatabaseManager.java
  holiholic_database/src/main/java/com/holiholic/database/controller/LoginController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/PeopleController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/PostController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/QuestionsController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/TopicsController.java
  holiholic_database/src/main/java/com/holiholic/database/feed/Comment.java
  holiholic_database/src/main/java/com/holiholic/database/feed/Feed.java
  holiholic_feed/src/main/java/com/holiholic/feed/controller/PostController.java
  holiholic_feed/src/main/java/com/holiholic/feed/controller/QuestionsController.java
  holiholic_feed/src/main/java/com/holiholic/feed/database/DatabaseManager.java
  holiholic_follow/src/main/java/com/holiholic/follow/constant/Constants.java
  holiholic_follow/src/main/java/com/holiholic/follow/controllers/PeopleController.java
  holiholic_follow/src/main/java/com/holiholic/follow/controllers/TopicsController.java
  holiholic_follow/src/main/java/com/holiholic/follow/database/DatabaseManager.java
  holiholic_follow/src/main/java/com/holiholic/follow/follow/PeopleManager.java
  holiholic_follow/src/main/java/com/holiholic/follow/follow/TopicsManager.java
  holiholic_login/src/main/java/com/holiholic/login/constant/Constants.java
  holiholic_login/src/main/java/com/holiholic/login/database/DatabaseManager.java
  holiholic_login/src/main/java/com/holiholic/login/login/LoginManager.java
Labels: refactor

#6 [HH-6][GUIDE] Add guide module
  holiholic_database/src/main/java/com/holiholic/database/DatabaseManager.java
  holiholic_database/src/main/java/com/holiholic/database/constant/Constants.java
  holiholic_database/src/main/java/com/holiholic/database/controller/GuideController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/QuestionController.java
  holiholic_database/src/main/java/com/holiholic/database/controller/TopicController.java
  holiholic_database/src/main/java/com/holiholic/database/feed/Feed.java
  holiholic_database/src/main/java/com/holiholic/database/feed/Guide.java
  holiholic_feed/src/main/java/com/holiholic/feed/constant/Constants.java
  holiholic_feed/src/main/java/com/holiholic/feed/controller/GuideController.java
  holiholic_feed/src/main/java/com/holiholic/feed/database/DatabaseManager.java
Labels: enhancement, in progress

#9 [HH-9][PLANNER] Refactor database operations
  holiholic_planner/.gitignore
  holiholic_planner/db_backup/bucharest.json
  holiholic_planner/db_backup/bucharest_driving.txt
  holiholic_planner/db_backup/bucharest_restaurants.json
  holiholic_planner/db_backup/bucharest_traffic.txt
  holiholic_planner/db_backup/bucharest_walking.txt
  holiholic_planner/db_backup/bucharest_weather.txt
  holiholic_planner/pom.xml
  holiholic_planner/scripts/src/main/java/UpdateManager.java
  holiholic_planner/src/main/java/com/holiholic/planner/constant/Constants.java
  holiholic_planner/src/main/java/com/holiholic/planner/controllers/PlacesController.java
  holiholic_planner/src/main/java/com/holiholic/planner/controllers/PlannerController.java
  holiholic_planner/src/main/java/com/holiholic/planner/database/DatabaseManager.java
  holiholic_planner/src/main/java/com/holiholic/planner/planner/PlanManager.java
Labels: enhancement
